GET http://localhost:5000/api/v1/ HTTP/1.1

###

GET http://localhost:5000/api/v1/tasks HTTP/1.1

###
GET http://localhost:5000/api/v1/tasks?finish=&due_date=&priority=low&order=asc HTTP/1.1

###

POST http://localhost:5000/api/v1/tasks HTTP/1.1
content-type: application/json

{
    "description": "test due_date1 2",
    "due_date": "2024-02-11" ,
    "priority": "high" 
}

###
PUT http://localhost:5000/api/v1/tasks/67acb66c6087cfc3f8da9afc HTTP/1.1
content-type: application/json

{
    "description": "test due_date1 edit",
    "finish": true,
    "due_date": "2024-02-20"    ,
    "priority": "medium"
}

###
DELETE http://localhost:5000/api/v1/tasks/6793146559b5705b910f7ff3 HTTP/1.1

###
GET http://localhost:5000/api/v1/tasks/sudo HTTP/1.1

# 6793146559b5705b910f7ff3
# 67931f69cf57294a8b6cc0ea