GET http://localhost:5000/api/v1/ HTTP/1.1

###

GET http://localhost:5000/api/v1/tasks HTTP/1.1

###
GET http://localhost:5000/api/v1/tasks?finish=&due_date=&order=asc HTTP/1.1

###

POST http://localhost:5000/api/v1/tasks HTTP/1.1
content-type: application/json

{
    "description": "test due_date2",
    "due_date": "2024-02-11" 
}

###
PUT http://localhost:5000/api/v1/tasks/67ac608cc284edefa3ad584b HTTP/1.1
content-type: application/json

{
    "description": "test due_date2 edit",
    "finish": true,
    "due_date": "2024-02-20"    
}

###
DELETE http://localhost:5000/api/v1/tasks/6793146559b5705b910f7ff3 HTTP/1.1

###
GET http://localhost:5000/api/v1/tasks/sudo HTTP/1.1

# 6793146559b5705b910f7ff3
# 67931f69cf57294a8b6cc0ea